---
- name: Update packages
  apt:
    update_cache: yes
  tags:
    - system

- name: Install pm2
  shell: npm install pm2 -g

- name: Create backend directory
  file:
    path: ~/backend
    state: directory

- name: install tar
  apt:
    name: ["tar"]
    state: present

- name: Unpack the artefact
  shell: tar -czvf artifact.tar.gz ~/backend
  args:
    chdir: ~/backend

- name: install the application
  shell: npm install && pm2 start npm -- start
  args:
    chdir: ~/backend
