---
- name: Update packages
  apt:
    update_cache: yes
  tags:
    - system

- name: Install pm2
  shell: npm install pm2 -g

- name: Create backend directory
  file:
    path: ~/backend
    state: directory

- name: Unpack the artefact
  shell: apt install dtrx && dtrx artifact.tar.gz
  args:
    chdir: ~/backend

- name: install the application
  shell: npm install && pm2 start npm -- start
  args:
    chdir: ~/backend
