---
- name: Update packages
  apt:
    update_cache: yes
  tags:
    - system

- name: Install pm2
  shell: npm install pm2 -g

- name: Create backend directory
  file:
    path: ~/backend
    state: directory

- name: install tar
  apt:
    name: ["tar"]
    state: present

- name: copy tar
  copy:
    src: artifact.tar.gz
    dest: /tmp/

- name: Unpack the artefact
  shell: tar -xf /tmp/artifact.tar.gz  -C ~/backend
  args:
    chdir: ~/backend

- name: assign env
  shell: mv .env.fix .env
  args:
    chdir: ~/backend

- name: install the application
  shell: npm install
  args:
    chdir: ~/backend

- name: run the application
  shell: pm2 start npm -- start
  args:
    chdir: ~/backend
